### ISSUE TITLE
Completed adapter/serializer tutorial but repo request not working

### ISSUE THREAD

**Issue by danaoira** [danaoira/hello-ember#3]
Finished tutorial, but calling list of repos does not pull data from the API.

- Tutorial: https://emberigniter.com/fit-any-backend-into-ember-custom-adapters-serializers/
- GitHub API URL: https://api.github.com/users/danaoira
- repos_url: https://api.github.com/users/danaoira/repos

Repository model shows no data pulled:

![image](https://user-images.githubusercontent.com/2514403/28742897-e6870828-73f0-11e7-8d48-d61e7aceaf50.png)

**Comment by danaoira** [comment]
Opened issue on @frank06 repository.

https://github.com/frank06/ember-github-adapter/issues/2

**Comment by tonyhschu** [comment]
Here's how to think about debugging:

1. Can you get the data manually (i.e. via Postman) What parameters did you need to use to get the data? If you are about to do that...
2. Did the request actually go out in the browser. (Check the network tab in google chrome.) If it did...
3. Did it fail? Was there an error logged somewhere?...

Think through in detail how you might break the process down into little pieces that you can verify individually.

I'll talk to you later today to see how else I might help.
